### ISSUE TITLE
saltycircle funktioniert nicht

### ISSUE THREAD

**Issue by DiloAbi** [EgoPvP/erp_saltycircle#1]
Guten Tag, ich hab die neuste Version von SaltyChat installiert auf dem Server, leider zeigt es mir aber keinen Circle an wenn ich die Range ändere

**Comment by ZockerBoysHD** [comment]
In all Our Tests the script works 100%.

Without proper  error reporting and log reporting i wont be able to help you.

Also i dont know your whole setup. Itd be best, if you would Debug it step by step using print  as an example

**Comment by Thodde26** [comment]
I have the same problem the marker will not work
![RedM_b1436_GTAProcess_KPRdkWdE1o](https://user-images.githubusercontent.com/2639719/153356487-57cbe582-17b5-4cd5-87fb-821eb6130cd4.png)

Best Regrades
Thodde26

**Comment by ZockerBoysHD** [comment]
Due to no answer  from the of poster  this will be closed
